/**
 * P5 class kits as content (CLASSES.md §1 Warrior, §3 Rogue) plus the four
 * basic combo chains migrated from @dawned/shared BASIC_COMBOS (COMBAT.md §3
 * as-built note). clipSeconds are the REAL baked UAL durations. Authored
 * through the admin API by author-kits.mjs — the editor path end to end.
 *
 * Deviations from the doc table (flagged there at P5-E):
 * - Fan of Knives grants its combo point unconditionally (the schema has no
 *   "if ≥2 hit" conditional yet — revisit with P6's effect conditions).
 */

const warrior = [
  {
    id: 'ability_warrior_crushing_blow',
    classId: 'warrior',
    binding: { kind: 'slot', slot: 1 },
    name: 'Crushing Blow',
    icon: 'lorc/hammer-drop',
    description: 'A heavy overhand strike for #{1} damage that builds stagger.',
    unlockLevel: 1,
    cost: { type: 'rage', amount: 25 },
    cooldownMs: 0,
    targeting: { kind: 'melee_arc', angleDeg: 90, reach: 3 },
    effects: [{ kind: 'damage', coef: 1.6, school: 'physical', staggerBonus: 20 }],
    anim: { clip: 'Sword_Attack', clipSeconds: 1.533, durationMs: 900, contactFraction: 0.55 },
    sfx: 'impact_heavy',
  },
  {
    id: 'ability_warrior_shield_bash',
    classId: 'warrior',
    binding: { kind: 'slot', slot: 2 },
    name: 'Shield Bash',
    icon: 'delapouite/shield-bash',
    description: 'Slam the shield forward: #{1} damage, stuns and interrupts.',
    unlockLevel: 3,
    cost: { type: 'rage', amount: 20 },
    cooldownMs: 10000,
    targeting: { kind: 'melee_arc', angleDeg: 60, reach: 2.5 },
    effects: [
      { kind: 'damage', coef: 0.8, school: 'physical' },
      { kind: 'stun', durationMs: 1500 },
      { kind: 'interrupt' },
    ],
    anim: { clip: 'Shield_OneShot', clipSeconds: 0.833, durationMs: 550, contactFraction: 0.5 },
    sfx: 'impact',
  },
  {
    id: 'ability_warrior_charge',
    classId: 'warrior',
    binding: { kind: 'slot', slot: 3 },
    name: 'Charge',
    icon: 'delapouite/charging-bull',
    description: 'Rush 12 m forward — #{1} damage on impact, slows, builds Rage.',
    unlockLevel: 6,
    cost: { type: 'none', amount: 0 },
    cooldownMs: 12000,
    targeting: { kind: 'dash', distance: 12, speed: 24, stopOnHit: true },
    effects: [
      { kind: 'damage', coef: 0.5, school: 'physical' },
      {
        kind: 'apply_effect',
        target: 'hit',
        effectId: 'slow_charge',
        durationMs: 3000,
        stacksMax: 1,
        mods: { moveSpeedPct: -30 },
      },
      { kind: 'resource', resource: 'rage', amount: 15 },
    ],
    anim: { clip: 'Shield_Dash', clipSeconds: 1.1, durationMs: 700, contactFraction: 0.9 },
    sfx: 'dodge',
  },
  {
    id: 'ability_warrior_rending_slash',
    classId: 'warrior',
    binding: { kind: 'slot', slot: 4 },
    name: 'Rending Slash',
    icon: 'lorc/bleeding-wound',
    description: 'Tear armor open: #{1} damage plus a deep bleed.',
    unlockLevel: 10,
    cost: { type: 'rage', amount: 30 },
    cooldownMs: 8000,
    targeting: { kind: 'melee_arc', angleDeg: 90, reach: 3 },
    effects: [
      { kind: 'damage', coef: 0.9, school: 'physical' },
      {
        kind: 'apply_effect',
        target: 'hit',
        effectId: 'bleed_rending',
        durationMs: 9000,
        stacksMax: 1,
        mods: {
          periodic: { kind: 'damage', coefTotal: 0.9, school: 'physical', tickEveryMs: 1500 },
        },
      },
    ],
    anim: {
      clip: 'Sword_Attack_Standing',
      clipSeconds: 1.533,
      durationMs: 800,
      contactFraction: 0.55,
    },
    sfx: 'impact',
  },
  {
    id: 'ability_warrior_taunting_shout',
    classId: 'warrior',
    binding: { kind: 'slot', slot: 5 },
    name: 'Taunting Shout',
    icon: 'lorc/shouting',
    description: 'Bellow a challenge: nearby enemies attack YOU and hit softer.',
    unlockLevel: 14,
    cost: { type: 'none', amount: 0 },
    cooldownMs: 15000,
    targeting: { kind: 'pbaoe', radius: 8, ticks: { count: 1, everyMs: 500 } },
    effects: [
      { kind: 'taunt', durationMs: 3000 },
      {
        kind: 'apply_effect',
        target: 'hit',
        effectId: 'debuff_taunting_shout',
        durationMs: 6000,
        stacksMax: 1,
        mods: { damageDealtPct: -10 },
      },
    ],
    anim: { clip: 'Counter_Angry', clipSeconds: 2, durationMs: 1100, contactFraction: 0.4 },
    threatMult: 2.5,
    sfx: 'hurt',
  },
  {
    id: 'ability_warrior_whirlwind',
    classId: 'warrior',
    binding: { kind: 'slot', slot: 6 },
    name: 'Whirlwind',
    icon: 'lorc/whirlwind',
    description: 'Spin twice, hitting everything around you for #{1} per spin.',
    unlockLevel: 18,
    cost: { type: 'rage', amount: 40 },
    cooldownMs: 12000,
    targeting: { kind: 'pbaoe', radius: 4, ticks: { count: 2, everyMs: 500 } },
    effects: [{ kind: 'damage', coef: 1.1, school: 'physical' }],
    anim: {
      clip: 'Sword_Heavy_Combo',
      clipSeconds: 4.333,
      durationMs: 1800,
      contactFraction: 0.4,
      moveSpeedMult: 0.7,
    },
    sfx: 'impact',
  },
  {
    id: 'ability_warrior_shield_wall',
    classId: 'warrior',
    binding: { kind: 'slot', slot: 7 },
    name: 'Shield Wall',
    icon: 'lorc/edged-shield',
    description: 'Brace behind the shield: half damage, immovable, for 6 s.',
    unlockLevel: 22,
    cost: { type: 'none', amount: 0 },
    cooldownMs: 45000,
    onGcd: false,
    targeting: { kind: 'self' },
    effects: [
      {
        kind: 'apply_effect',
        target: 'self',
        effectId: 'buff_shield_wall',
        durationMs: 6000,
        stacksMax: 1,
        mods: { damageTakenPct: -50, knockbackImmune: true },
      },
    ],
    anim: { clip: 'Shield_OneShot', clipSeconds: 0.833, durationMs: 700, contactFraction: 0.3 },
    sfx: 'dodge',
  },
  {
    id: 'ability_warrior_earthshatter',
    classId: 'warrior',
    binding: { kind: 'slot', slot: 8 },
    name: 'Earthshatter',
    icon: 'lorc/quake-stomp',
    description: 'ULTIMATE: shatter the ground — massive cone damage, knockdown.',
    unlockLevel: 25,
    cost: { type: 'rage', amount: 50 },
    cooldownMs: 60000,
    targeting: { kind: 'cone', angleDeg: 120, reach: 6 },
    effects: [
      { kind: 'damage', coef: 2.5, school: 'physical', staggerBonus: 100 },
      { kind: 'knockdown', durationMs: 2000 },
    ],
    anim: { clip: 'Sword_Attack', clipSeconds: 1.533, durationMs: 1000, contactFraction: 0.6 },
    sfx: 'impact_crit',
  },
];

const rogue = [
  {
    id: 'ability_rogue_twin_strike',
    classId: 'rogue',
    binding: { kind: 'slot', slot: 1 },
    name: 'Twin Strike',
    icon: 'lorc/crossed-swords',
    description: 'Both daggers at once: 2 × #{1} damage. Awards a combo point.',
    unlockLevel: 1,
    cost: { type: 'energy', amount: 25 },
    cooldownMs: 0,
    comboPointGain: 1,
    targeting: { kind: 'melee_arc', angleDeg: 70, reach: 2.5 },
    effects: [
      { kind: 'damage', coef: 0.6, school: 'physical', hits: 2 },
      { kind: 'resource', resource: 'energy', amount: 0, comboPoints: 1 },
    ],
    anim: { clip: 'Sword_Regular_A', clipSeconds: 0.433, durationMs: 450, contactFraction: 0.55 },
    sfx: 'impact',
  },
  {
    id: 'ability_rogue_shadowstep',
    classId: 'rogue',
    binding: { kind: 'slot', slot: 2 },
    name: 'Shadowstep',
    icon: 'lorc/shadow-follower',
    description: 'Vanish and reappear behind your target. Next attack +20%.',
    unlockLevel: 3,
    cost: { type: 'energy', amount: 20 },
    cooldownMs: 10000,
    comboPointGain: 1,
    targeting: { kind: 'blink_behind', maxRange: 12 },
    effects: [
      { kind: 'resource', resource: 'energy', amount: 0, comboPoints: 1 },
      {
        kind: 'apply_effect',
        target: 'self',
        effectId: 'buff_shadowstep',
        durationMs: 6000,
        stacksMax: 1,
        mods: { nextAttackPct: 20 },
      },
    ],
    anim: { clip: 'Sword_Enter', clipSeconds: 1.3, durationMs: 700, contactFraction: 0.5 },
    sfx: 'dodge',
  },
  {
    id: 'ability_rogue_eviscerate',
    classId: 'rogue',
    binding: { kind: 'slot', slot: 3 },
    name: 'Eviscerate',
    icon: 'lorc/bloody-sword',
    description: 'FINISHER: #{1} damage plus #{2} per combo point spent.',
    unlockLevel: 6,
    cost: { type: 'energy', amount: 30 },
    cooldownMs: 0,
    comboFinisher: true,
    targeting: { kind: 'melee_arc', angleDeg: 60, reach: 2.5 },
    effects: [{ kind: 'damage', coef: 0.9, school: 'physical', coefPerComboPoint: 0.5 }],
    anim: {
      clip: 'Sword_Attack_Standing',
      clipSeconds: 1.533,
      durationMs: 850,
      contactFraction: 0.55,
    },
    sfx: 'impact_crit',
  },
  {
    id: 'ability_rogue_fan_of_knives',
    classId: 'rogue',
    binding: { kind: 'slot', slot: 4 },
    name: 'Fan of Knives',
    icon: 'lorc/thrown-daggers',
    description: 'A fan of thrown steel: #{1} damage to everything in front.',
    unlockLevel: 10,
    cost: { type: 'energy', amount: 30 },
    cooldownMs: 8000,
    comboPointGain: 1,
    targeting: { kind: 'cone', angleDeg: 90, reach: 8, visual: 'knives' },
    effects: [
      { kind: 'damage', coef: 0.7, school: 'physical' },
      { kind: 'resource', resource: 'energy', amount: 0, comboPoints: 1 },
    ],
    anim: { clip: 'OverhandThrow', clipSeconds: 1.333, durationMs: 800, contactFraction: 0.5 },
    sfx: 'bolt',
  },
  {
    id: 'ability_rogue_crippling_strike',
    classId: 'rogue',
    binding: { kind: 'slot', slot: 5 },
    name: 'Crippling Strike',
    icon: 'lorc/broken-bone',
    description: 'Hamstring the target: #{1} damage and a heavy slow.',
    unlockLevel: 14,
    cost: { type: 'energy', amount: 20 },
    cooldownMs: 6000,
    comboPointGain: 1,
    targeting: { kind: 'melee_arc', angleDeg: 70, reach: 2.5 },
    effects: [
      { kind: 'damage', coef: 0.7, school: 'physical' },
      {
        kind: 'apply_effect',
        target: 'hit',
        effectId: 'slow_crippling',
        durationMs: 5000,
        stacksMax: 1,
        mods: { moveSpeedPct: -40 },
      },
      { kind: 'resource', resource: 'energy', amount: 0, comboPoints: 1 },
    ],
    anim: { clip: 'Sword_Regular_C', clipSeconds: 2, durationMs: 850, contactFraction: 0.55 },
    sfx: 'impact',
  },
  {
    id: 'ability_rogue_poisoned_blades',
    classId: 'rogue',
    binding: { kind: 'slot', slot: 6 },
    name: 'Poisoned Blades',
    icon: 'lorc/dripping-knife',
    description: 'Coat both blades: attacks apply stacking poison for 12 s.',
    unlockLevel: 18,
    cost: { type: 'energy', amount: 25 },
    cooldownMs: 20000,
    targeting: { kind: 'self' },
    effects: [
      {
        kind: 'apply_effect',
        target: 'self',
        effectId: 'buff_poisoned_blades',
        durationMs: 12000,
        stacksMax: 1,
        mods: {
          onHitApply: {
            effectId: 'poison_blades',
            durationMs: 6000,
            stacksMax: 3,
            periodic: { kind: 'damage', coefTotal: 0.25, school: 'physical', tickEveryMs: 1500 },
          },
        },
      },
    ],
    anim: { clip: 'Sword_Enter', clipSeconds: 1.3, durationMs: 800, contactFraction: 0.5 },
    sfx: 'dodge',
  },
  {
    id: 'ability_rogue_smoke_veil',
    classId: 'rogue',
    binding: { kind: 'slot', slot: 7 },
    name: 'Smoke Veil',
    icon: 'darkzaitzev/smoke-bomb',
    description: 'Drop into smoke: enemies lose you, you move faster, strike harder.',
    unlockLevel: 22,
    cost: { type: 'energy', amount: 25 },
    cooldownMs: 40000,
    onGcd: false,
    targeting: { kind: 'self' },
    effects: [
      {
        kind: 'apply_effect',
        target: 'self',
        effectId: 'buff_smoke_veil',
        durationMs: 3000,
        stacksMax: 1,
        mods: { threatDrop: true, moveSpeedPct: 30, nextAttackPct: 30 },
      },
    ],
    anim: { clip: 'OverhandThrow', clipSeconds: 1.333, durationMs: 700, contactFraction: 0.4 },
    sfx: 'dodge',
  },
  {
    id: 'ability_rogue_death_mark',
    classId: 'rogue',
    binding: { kind: 'slot', slot: 8 },
    name: 'Death Mark',
    icon: 'lorc/targeting',
    description:
      'ULTIMATE: mark a victim — they take more from you; a marked kill refunds everything.',
    unlockLevel: 25,
    cost: { type: 'energy', amount: 40 },
    cooldownMs: 60000,
    targeting: { kind: 'single', maxRange: 15 },
    effects: [
      { kind: 'damage', coef: 1.5, school: 'physical' },
      {
        kind: 'mark',
        durationMs: 8000,
        damageFromCasterPct: 20,
        onKill: { energy: 50, resetCooldownOf: 'ability_rogue_shadowstep' },
      },
    ],
    anim: { clip: 'OverhandThrow', clipSeconds: 1.333, durationMs: 700, contactFraction: 0.5 },
    sfx: 'impact_crit',
  },
];

/** Basic combo chains (COMBAT.md §3) — migrated from shared BASIC_COMBOS. */
const BASIC_ICONS = {
  warrior: 'lorc/broadsword',
  rogue: 'lorc/plain-dagger',
  mage: 'lorc/energy-arrow',
  cleric: 'lorc/holy-symbol',
};

const basicStep = (classId, step, overrides) => ({
  id: `ability_${classId}_basic_${step}`,
  classId,
  binding: { kind: 'basic', step },
  icon: BASIC_ICONS[classId],
  unlockLevel: 1,
  cost: { type: 'none', amount: 0 },
  cooldownMs: 0,
  ...overrides,
});

const basics = [
  ...[
    { step: 1, coef: 0.55, clip: 'Sword_Regular_A', clipSeconds: 0.433, durationMs: 450 },
    { step: 2, coef: 0.55, clip: 'Sword_Regular_B', clipSeconds: 0.533, durationMs: 500 },
    { step: 3, coef: 0.85, clip: 'Sword_Regular_C', clipSeconds: 2, durationMs: 750 },
  ].map(({ step, coef, clip, clipSeconds, durationMs }) =>
    basicStep('warrior', step, {
      name: `Sword Combo ${step}`,
      targeting:
        step === 3
          ? { kind: 'melee_arc', angleDeg: 120, reach: 2.6 }
          : { kind: 'melee_arc', angleDeg: 70, reach: 2.6 },
      effects: [
        { kind: 'damage', coef, school: 'physical', staggerBonus: step === 3 ? 12 : 0 },
        { kind: 'resource', resource: 'rage', amount: 4 },
      ],
      anim: { clip, clipSeconds, durationMs, contactFraction: 0.55 },
    }),
  ),
  ...[
    { step: 1, coef: 0.45, clip: 'Sword_Regular_A', clipSeconds: 0.433, durationMs: 400 },
    { step: 2, coef: 0.45, clip: 'Sword_Regular_B', clipSeconds: 0.533, durationMs: 450 },
    { step: 3, coef: 0.7, clip: 'Sword_Regular_C', clipSeconds: 2, durationMs: 650 },
  ].map(({ step, coef, clip, clipSeconds, durationMs }) =>
    basicStep('rogue', step, {
      name: `Dagger Flurry ${step}`,
      comboPointGain: step === 3 ? 1 : 0,
      targeting: { kind: 'melee_arc', angleDeg: 70, reach: 2.3 },
      effects:
        step === 3
          ? [
              { kind: 'damage', coef, school: 'physical', staggerBonus: 8 },
              { kind: 'resource', resource: 'energy', amount: 0, comboPoints: 1 },
            ]
          : [{ kind: 'damage', coef, school: 'physical' }],
      anim: { clip, clipSeconds, durationMs, contactFraction: 0.55 },
    }),
  ),
  ...['mage', 'cleric'].flatMap((classId) =>
    [
      { step: 1, coef: 0.5, durationMs: 500 },
      { step: 2, coef: 0.5, durationMs: 500 },
      { step: 3, coef: 0.75, durationMs: 650 },
    ].map(({ step, coef, durationMs }) =>
      basicStep(classId, step, {
        name: `${classId === 'mage' ? 'Arc Bolt' : 'Holy Spark'} ${step}`,
        targeting: { kind: 'projectile', speed: 28, radius: 0.25, maxRange: 30 },
        effects: [{ kind: 'damage', coef, school: 'magic', staggerBonus: step === 3 ? 10 : 0 }],
        anim: {
          clip: 'Spell_Simple_Shoot',
          clipSeconds: 0.5,
          durationMs,
          contactFraction: 0.6,
        },
      }),
    ),
  ),
];

/**
 * P6 caster kits (CLASSES.md §2 Mage, §4 Cleric). Cast-loop visuals are a
 * client rule (Spell_*_Idle_Loop while the bar runs); anim here is the
 * RELEASE/commit read. Blink's ghost window is 500 ms (schema floor; doc says
 * 0.3 s — flagged in the P6-C notes).
 */
const mage = [
  {
    id: 'ability_mage_fireball',
    classId: 'mage',
    binding: { kind: 'slot', slot: 1 },
    name: 'Fireball',
    icon: 'lorc/fireball',
    description: 'Hurl fire for #{1} damage that keeps burning.',
    unlockLevel: 1,
    cost: { type: 'mana', amount: 20 },
    cooldownMs: 0,
    castMs: 1200,
    castWhileMoving: 0.6,
    targeting: { kind: 'projectile', speed: 22, radius: 0.4, maxRange: 30 },
    effects: [
      { kind: 'damage', coef: 1.8, school: 'magic' },
      {
        kind: 'apply_effect',
        target: 'hit',
        effectId: 'burn_fireball',
        durationMs: 6000,
        category: 'burn',
        mods: { periodic: { kind: 'damage', school: 'magic', coefTotal: 0.4, tickEveryMs: 1500 } },
      },
    ],
    anim: { clip: 'Spell_Simple_Shoot', clipSeconds: 0.5, durationMs: 500, contactFraction: 0.6 },
    sfx: 'bolt',
  },
  {
    id: 'ability_mage_ice_lance',
    classId: 'mage',
    binding: { kind: 'slot', slot: 2 },
    name: 'Ice Lance',
    icon: 'lorc/ice-spear',
    description: 'A fast shard: #{1} damage, chills — +50% vs chilled or rooted.',
    unlockLevel: 3,
    cost: { type: 'mana', amount: 15 },
    cooldownMs: 0,
    targeting: { kind: 'projectile', speed: 35, radius: 0.25, maxRange: 30 },
    effects: [
      {
        kind: 'damage',
        coef: 1.0,
        school: 'magic',
        bonusVs: { categories: ['chill', 'root'], pct: 50 },
      },
      {
        kind: 'apply_effect',
        target: 'hit',
        effectId: 'chill_lance',
        durationMs: 4000,
        category: 'chill',
        mods: { moveSpeedPct: -20 },
      },
    ],
    anim: { clip: 'Spell_Simple_Shoot', clipSeconds: 0.5, durationMs: 450, contactFraction: 0.6 },
    sfx: 'bolt',
  },
  {
    id: 'ability_mage_frost_nova',
    classId: 'mage',
    binding: { kind: 'slot', slot: 3 },
    name: 'Frost Nova',
    icon: 'lorc/frozen-orb',
    description: 'Ice erupts around you: #{1} damage and a 2 s root.',
    unlockLevel: 6,
    cost: { type: 'mana', amount: 25 },
    cooldownMs: 14000,
    targeting: { kind: 'pbaoe', radius: 5 },
    effects: [
      { kind: 'damage', coef: 0.7, school: 'magic' },
      { kind: 'root', durationMs: 2000 },
    ],
    anim: {
      clip: 'Spell_Double_Shoot_Loop',
      clipSeconds: 0.267,
      durationMs: 600,
      contactFraction: 0.5,
    },
    sfx: 'impact',
  },
  {
    id: 'ability_mage_blink',
    classId: 'mage',
    binding: { kind: 'slot', slot: 4 },
    name: 'Blink',
    icon: 'lorc/teleport',
    description: 'Vanish 10 m forward — breaks roots and slows.',
    unlockLevel: 10,
    cost: { type: 'mana', amount: 10 },
    cooldownMs: 12000,
    onGcd: false,
    targeting: { kind: 'teleport', distance: 10 },
    effects: [
      { kind: 'cleanse', category: 'movement', all: true },
      {
        kind: 'apply_effect',
        target: 'self',
        effectId: 'buff_blink_ghost',
        durationMs: 500,
        mods: { untargetable: true },
      },
    ],
    anim: { clip: 'Spell_Simple_Exit', clipSeconds: 0.433, durationMs: 450, contactFraction: 0.5 },
    sfx: 'dodge',
  },
  {
    id: 'ability_mage_ember_wave',
    classId: 'mage',
    binding: { kind: 'slot', slot: 5 },
    name: 'Ember Wave',
    icon: 'lorc/fire-wave',
    description: 'A sweep of flame: #{1} damage and every burn flares anew.',
    unlockLevel: 14,
    cost: { type: 'mana', amount: 30 },
    cooldownMs: 10000,
    castMs: 800,
    castWhileMoving: 0.6,
    targeting: { kind: 'cone', angleDeg: 60, reach: 7 },
    effects: [
      { kind: 'damage', coef: 1.4, school: 'magic' },
      { kind: 'refresh', category: 'burn' },
    ],
    anim: {
      clip: 'Spell_Double_Shoot_Loop',
      clipSeconds: 0.267,
      durationMs: 500,
      contactFraction: 0.6,
    },
    sfx: 'impact',
  },
  {
    id: 'ability_mage_mana_shield',
    classId: 'mage',
    binding: { kind: 'slot', slot: 6 },
    name: 'Mana Shield',
    icon: 'lorc/magic-shield',
    description: 'Damage drains Mana instead of blood — until the well runs dry.',
    unlockLevel: 18,
    cost: { type: 'mana', amount: 15 },
    cooldownMs: 8000,
    onGcd: false,
    targeting: { kind: 'self' },
    effects: [
      {
        kind: 'apply_effect',
        target: 'self',
        effectId: 'buff_mana_shield',
        durationMs: 30000,
        mods: { manaShieldPerPoint: 2 },
      },
    ],
    anim: { clip: 'Spell_Simple_Enter', clipSeconds: 0.533, durationMs: 550, contactFraction: 0.5 },
    sfx: 'dodge',
  },
  {
    id: 'ability_mage_arcane_barrage',
    classId: 'mage',
    binding: { kind: 'slot', slot: 7 },
    name: 'Arcane Barrage',
    icon: 'lorc/missile-swarm',
    description: 'Channel a swarm: 6 homing bolts of #{1} damage each.',
    unlockLevel: 22,
    cost: { type: 'mana', amount: 35 },
    cooldownMs: 12000,
    channel: { durationMs: 2400, tickEveryMs: 400 },
    castWhileMoving: 0.4,
    targeting: { kind: 'projectile', speed: 30, radius: 0.3, maxRange: 30, homing: true },
    effects: [{ kind: 'damage', coef: 0.55, school: 'magic' }],
    anim: { clip: 'Spell_Double_Enter', clipSeconds: 0.633, durationMs: 650, contactFraction: 0.5 },
    sfx: 'bolt',
  },
  {
    id: 'ability_mage_meteor',
    classId: 'mage',
    binding: { kind: 'slot', slot: 8 },
    name: 'Meteor',
    icon: 'lorc/meteor-impact',
    description: 'ULTIMATE: mark the ground — the sky answers with #{1} damage.',
    unlockLevel: 25,
    cost: { type: 'mana', amount: 50 },
    cooldownMs: 60000,
    targeting: { kind: 'ground_aoe', radius: 5, maxRange: 25, telegraphMs: 1500 },
    effects: [
      { kind: 'damage', coef: 3.2, school: 'magic', staggerBonus: 40 },
      {
        kind: 'apply_effect',
        target: 'hit',
        effectId: 'burn_meteor',
        durationMs: 6000,
        category: 'burn',
        mods: { periodic: { kind: 'damage', school: 'magic', coefTotal: 0.4, tickEveryMs: 1500 } },
      },
    ],
    anim: { clip: 'Spell_Double_Enter', clipSeconds: 0.633, durationMs: 900, contactFraction: 0.6 },
    sfx: 'impact_crit',
  },
];

const cleric = [
  {
    id: 'ability_cleric_holy_smite',
    classId: 'cleric',
    binding: { kind: 'slot', slot: 1 },
    name: 'Holy Smite',
    icon: 'lorc/sunbeams',
    description: 'A bolt of dawn for #{1} damage. Feeds Grace.',
    unlockLevel: 1,
    cost: { type: 'mana', amount: 15 },
    cooldownMs: 0,
    targeting: { kind: 'projectile', speed: 28, radius: 0.25, maxRange: 30 },
    effects: [{ kind: 'damage', coef: 1.3, school: 'magic' }],
    anim: { clip: 'Spell_Simple_Shoot', clipSeconds: 0.5, durationMs: 500, contactFraction: 0.6 },
    sfx: 'bolt',
  },
  {
    id: 'ability_cleric_mend',
    classId: 'cleric',
    binding: { kind: 'slot', slot: 2 },
    name: 'Mend',
    icon: 'lorc/glowing-hands',
    description: 'Knit an ally (or yourself) back together for #{1}.',
    unlockLevel: 3,
    cost: { type: 'mana', amount: 25 },
    cooldownMs: 0,
    castMs: 1500,
    castWhileMoving: 0.6,
    targeting: { kind: 'ally_soft', range: 20 },
    effects: [{ kind: 'heal', coef: 2.2 }],
    anim: { clip: 'Spell_Simple_Shoot', clipSeconds: 0.5, durationMs: 500, contactFraction: 0.6 },
    sfx: 'dodge',
  },
  {
    id: 'ability_cleric_hammer_of_wrath',
    classId: 'cleric',
    binding: { kind: 'slot', slot: 3 },
    name: 'Hammer of Wrath',
    icon: 'delapouite/warhammer',
    description: 'The hammer falls: #{1} damage, staggers, and mends you a little.',
    unlockLevel: 6,
    cost: { type: 'mana', amount: 20 },
    cooldownMs: 8000,
    targeting: { kind: 'melee_arc', angleDeg: 90, reach: 3 },
    effects: [
      { kind: 'damage', coef: 1.4, school: 'magic', staggerBonus: 15 },
      { kind: 'heal', coef: 0.3 },
    ],
    anim: { clip: 'Sword_Attack', clipSeconds: 1.533, durationMs: 800, contactFraction: 0.55 },
    sfx: 'impact_heavy',
  },
  {
    id: 'ability_cleric_radiant_burst',
    classId: 'cleric',
    binding: { kind: 'slot', slot: 4 },
    name: 'Radiant Burst',
    icon: 'lorc/beams-aura',
    description: 'Light detonates: allies mend #{1}, enemies take #{2}.',
    unlockLevel: 10,
    cost: { type: 'mana', amount: 30 },
    cooldownMs: 12000,
    targeting: { kind: 'pbaoe', radius: 6 },
    effects: [
      { kind: 'heal', coef: 1.2 },
      { kind: 'damage', coef: 0.8, school: 'magic' },
    ],
    anim: {
      clip: 'Spell_Double_Shoot_Loop',
      clipSeconds: 0.267,
      durationMs: 600,
      contactFraction: 0.5,
    },
    sfx: 'impact',
  },
  {
    id: 'ability_cleric_sanctuary',
    classId: 'cleric',
    binding: { kind: 'slot', slot: 5 },
    name: 'Sanctuary',
    icon: 'lorc/aura',
    description: 'Consecrate the ground: allies inside mend for 8 s.',
    unlockLevel: 14,
    cost: { type: 'mana', amount: 35 },
    cooldownMs: 20000,
    targeting: { kind: 'ground_aoe', radius: 4, maxRange: 20 },
    effects: [
      {
        kind: 'zone',
        radius: 4,
        durationMs: 8000,
        tickEveryMs: 1000,
        team: 'allies',
        tick: { kind: 'heal', coef: 0.35 },
      },
    ],
    anim: { clip: 'Spell_Double_Enter', clipSeconds: 0.633, durationMs: 700, contactFraction: 0.5 },
    sfx: 'dodge',
  },
  {
    id: 'ability_cleric_purify',
    classId: 'cleric',
    binding: { kind: 'slot', slot: 6 },
    name: 'Purify',
    icon: 'lorc/star-swirl',
    description: 'Burn away one affliction and mend #{1}.',
    unlockLevel: 18,
    cost: { type: 'mana', amount: 15 },
    cooldownMs: 8000,
    targeting: { kind: 'ally_soft', range: 20 },
    effects: [
      { kind: 'cleanse', category: 'any', count: 1 },
      { kind: 'heal', coef: 0.6 },
    ],
    anim: { clip: 'Spell_Simple_Shoot', clipSeconds: 0.5, durationMs: 500, contactFraction: 0.6 },
    sfx: 'dodge',
  },
  {
    id: 'ability_cleric_aegis',
    classId: 'cleric',
    binding: { kind: 'slot', slot: 7 },
    name: 'Aegis',
    icon: 'lorc/bolt-shield',
    description: 'Wrap an ally in light that absorbs #{1} damage.',
    unlockLevel: 22,
    cost: { type: 'mana', amount: 30 },
    cooldownMs: 25000,
    targeting: { kind: 'ally_soft', range: 20 },
    effects: [{ kind: 'shield', coef: 2.0, durationMs: 8000 }],
    anim: { clip: 'Spell_Simple_Enter', clipSeconds: 0.533, durationMs: 550, contactFraction: 0.5 },
    sfx: 'dodge',
  },
  {
    id: 'ability_cleric_dawnlight',
    classId: 'cleric',
    binding: { kind: 'slot', slot: 8 },
    name: 'Dawnlight',
    icon: 'delapouite/sunrise',
    description: 'ULTIMATE: the dawn itself — mend #{1}, cleanse everything, sear foes.',
    unlockLevel: 25,
    cost: { type: 'mana', amount: 50 },
    cooldownMs: 75000,
    targeting: { kind: 'pbaoe', radius: 10 },
    effects: [
      { kind: 'heal', coef: 2.5 },
      { kind: 'cleanse', category: 'any', all: true },
      { kind: 'damage', coef: 1.5, school: 'magic', staggerBonus: 30 },
    ],
    anim: {
      clip: 'Spell_Double_Enter',
      clipSeconds: 0.633,
      durationMs: 1000,
      contactFraction: 0.5,
    },
    sfx: 'impact_crit',
  },
];

export const KIT_DEFS = [...warrior, ...rogue, ...mage, ...cleric, ...basics];
