/**
 * Whole-world terrain synthesis (MAP_EDITOR.md §2.1 "island mask synth", used to
 * seed the base world for game P12).
 *
 * Why this is not in `map-editor/generators.ts` with the other generators: those
 * run in the browser against the RESIDENT region, which is capped at 13×13
 * chunks. The Dawnlands are 32×32. An archipelago cannot be generated by a tool
 * that can only see a fifth of it, so the whole-world pass runs on the server —
 * and the math it runs has to be the same math the editor's own island button
 * runs, or the owner would be previewing one world and publishing another. That
 * is what this module is: the math, with no store, no journal and no fetch.
 *
 * Two things it does that the single-island generator cannot:
 *
 *  1. **Masks COMBINE rather than overwrite.** Each island contributes a height
 *     and the field takes the greatest. Where two discs overlap you get an
 *     isthmus instead of the second island erasing the first, which is the whole
 *     reason an archipelago can have a shape rather than being five circles.
 *  2. **Erosion crosses chunk seams.** The per-chunk version skips border
 *     vertices — correct, because adjacent chunks SHARE that row and a
 *     one-sided edit would tear the world — but that leaves an un-eroded grid
 *     every 64 m. Here the world is one height field and the seams are interior.
 */

const WORLD_CELLS_PER_CHUNK = 64;

/**
 * One mask's contribution to the height field.
 *
 * `carve` masks SUBTRACT. They exist because WORLD.md wants two things at once:
 * 55–60 % of the world to be land, and bridges to gate the path between isles.
 * Five landmasses big enough for the first cannot also be far enough apart for
 * the second — in a 2048 m box they overlap. So the isles are generated
 * overlapping and the straits are cut afterwards, which is also what a strait
 * IS. A carve slopes its banks by the same `1 - d²` falloff a dome rises with,
 * so a channel has beaches rather than trench walls.
 */
export interface IslandMask {
  /** Names the landmass for progress lines and for the report a run prints. */
  readonly id: string;
  /** `land` raises (default); `carve` cuts a channel through whatever is there. */
  readonly kind?: 'land' | 'carve';
  readonly seed: number;
  readonly centerX: number;
  readonly centerZ: number;
  /** Metres from centre to the shoreline. */
  readonly radius: number;
  /** Peak height above sea level. */
  readonly peak: number;
  /** 0 = smooth dome, 1 = ragged ridges. */
  readonly roughness: number;
  /**
   * Stretches the disc into an ellipse: >1 widens east-west. A world of perfect
   * circles reads as generated, which is the one thing WORLD.md §7's
   * "hand-dressed" promise cannot survive.
   */
  readonly stretchX?: number;
  readonly stretchZ?: number;
  /**
   * Rotates the ellipse, radians. Free to apply and it is what stops four
   * stretched isles from all lying the same way.
   */
  readonly rotation?: number;
}

export interface ErosionSettings {
  readonly passes: number;
  /** Only erode where it is steeper than this — flats stay flat. */
  readonly minSlopeDeg: number;
  /** 0–1 blend toward the neighbourhood average per pass. */
  readonly strength: number;
}

export const DEFAULT_WORLD_EROSION: ErosionSettings = {
  passes: 3,
  minSlopeDeg: 22,
  strength: 0.5,
};

/** Small deterministic PRNG — same seed, same island, on any machine. */
export const mulberry32 = (seed: number): (() => number) => {
  let a = seed >>> 0;
  return (): number => {
    a = (a + 0x6d2b79f5) >>> 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
};

/** Value noise with a smooth interpolant, tiled over a 256-entry gradient. */
export const makeNoise = (seed: number): ((x: number, z: number) => number) => {
  const random = mulberry32(seed);
  const table = new Float32Array(256);
  for (let i = 0; i < table.length; i++) table[i] = random();
  const hash = (x: number, z: number): number => table[(x * 73 + z * 151) & 255]!;
  const fade = (t: number): number => t * t * (3 - 2 * t);
  return (x: number, z: number): number => {
    const ix = Math.floor(x);
    const iz = Math.floor(z);
    const fx = fade(x - ix);
    const fz = fade(z - iz);
    const a = hash(ix, iz);
    const b = hash(ix + 1, iz);
    const c = hash(ix, iz + 1);
    const d = hash(ix + 1, iz + 1);
    return (a + (b - a) * fx) * (1 - fz) + (c + (d - c) * fx) * fz;
  };
};

/**
 * A single mask's height at a world position, or `null` where the mask does not
 * reach — the caller decides what "no land here" means, because an archipelago
 * has to tell "outside every island" (ocean floor) from "inside one at zero
 * height" (waterline).
 *
 * The falloff is `1 - d²` rather than `1 - d` so the shore arrives gently. A
 * linear cone gives a cliff at the waterline, which reads as an error rather
 * than a beach and makes the walkgrid a ring of Steep.
 */
export const maskHeightAt = (
  mask: IslandMask,
  noise: (x: number, z: number) => number,
  x: number,
  z: number,
  seaLevel: number,
): number | null => {
  let dx = x - mask.centerX;
  let dz = z - mask.centerZ;
  if (mask.rotation) {
    const cos = Math.cos(-mask.rotation);
    const sin = Math.sin(-mask.rotation);
    const rx = dx * cos - dz * sin;
    const rz = dx * sin + dz * cos;
    dx = rx;
    dz = rz;
  }
  dx /= mask.stretchX ?? 1;
  dz /= mask.stretchZ ?? 1;
  const d = Math.hypot(dx, dz) / mask.radius;
  if (d >= 1) return null;
  const dome = 1 - d * d;
  // Three octaves is enough for a readable silhouette and cheap enough that
  // regenerating the whole world stays a few seconds rather than a coffee.
  const detail =
    noise(x * 0.006, z * 0.006) * 0.6 +
    noise(x * 0.017, z * 0.017) * 0.3 +
    noise(x * 0.041, z * 0.041) * 0.1;
  return seaLevel + dome * mask.peak * (1 - mask.roughness * 0.5 + detail * mask.roughness);
};

/**
 * The whole world as one height field, so erosion and slope reads do not have to
 * care where the chunk boundaries are.
 *
 * `WORLD_CHUNKS × 64 + 1` vertices a side — the +1 because adjacent chunks SHARE
 * their border row. That sharing is the reason this class exists: writing a
 * border vertex in one chunk and not the other tears the world open, and the
 * only way to be sure that never happens is to not have two copies while the
 * maths is running.
 */
export class WorldHeightField {
  readonly side: number;
  readonly heights: Float32Array;

  constructor(
    readonly worldChunks: number,
    readonly originM: number,
  ) {
    this.side = worldChunks * WORLD_CELLS_PER_CHUNK + 1;
    this.heights = new Float32Array(this.side * this.side);
  }

  /** Vertex index → world metres (the grid is 1 m). */
  worldX(gx: number): number {
    return this.originM + gx;
  }

  worldZ(gz: number): number {
    return this.originM + gz;
  }

  get(gx: number, gz: number): number {
    return this.heights[gz * this.side + gx]!;
  }

  set(gx: number, gz: number, value: number): void {
    this.heights[gz * this.side + gx] = value;
  }

  /** Read a chunk's 65×65 window out of the field. */
  readChunk(cx: number, cy: number, out: Float32Array, verts: number): void {
    const baseX = cx * WORLD_CELLS_PER_CHUNK;
    const baseZ = cy * WORLD_CELLS_PER_CHUNK;
    for (let iz = 0; iz < verts; iz++) {
      const row = (baseZ + iz) * this.side + baseX;
      for (let ix = 0; ix < verts; ix++) out[iz * verts + ix] = this.heights[row + ix]!;
    }
  }

  /** Write a chunk's 65×65 window into the field (shared borders overwrite). */
  writeChunk(cx: number, cy: number, heights: Float32Array, verts: number): void {
    const baseX = cx * WORLD_CELLS_PER_CHUNK;
    const baseZ = cy * WORLD_CELLS_PER_CHUNK;
    for (let iz = 0; iz < verts; iz++) {
      const row = (baseZ + iz) * this.side + baseX;
      for (let ix = 0; ix < verts; ix++) this.heights[row + ix] = heights[iz * verts + ix]!;
    }
  }
}

export interface SynthReport {
  /** Vertices that ended up above the waterline. */
  land: number;
  /** Per-island land vertex counts, so a mask that drowned is visible. */
  perIsland: Record<string, number>;
}

/**
 * Write every vertex of the field from the masks: the greatest contribution
 * wins, and anywhere no mask reaches becomes ocean floor.
 *
 * Taking the MAX (rather than a sum) is what makes an overlap read as a saddle
 * between two hills instead of a spike twice as tall as either.
 */
export const synthWorld = (
  field: WorldHeightField,
  masks: readonly IslandMask[],
  seaLevel: number,
  oceanFloor: number,
): SynthReport => {
  const lands = masks.filter((mask) => mask.kind !== 'carve');
  const carves = masks.filter((mask) => mask.kind === 'carve');
  const landNoises = lands.map((mask) => makeNoise(mask.seed));
  const carveNoises = carves.map((mask) => makeNoise(mask.seed));
  const perIsland: Record<string, number> = {};
  for (const mask of lands) perIsland[mask.id] = 0;
  let land = 0;
  for (let gz = 0; gz < field.side; gz++) {
    const z = field.worldZ(gz);
    for (let gx = 0; gx < field.side; gx++) {
      const x = field.worldX(gx);
      let best = Number.NEGATIVE_INFINITY;
      let bestId: string | null = null;
      for (let i = 0; i < lands.length; i++) {
        const height = maskHeightAt(lands[i]!, landNoises[i]!, x, z, seaLevel);
        if (height === null || height <= best) continue;
        best = height;
        bestId = lands[i]!.id;
      }
      if (bestId === null) {
        field.set(gx, gz, oceanFloor);
        continue;
      }
      // Carves cut AFTER the land is composed: a strait has to be able to sever
      // an isthmus the masks just merged, which it cannot do if it competes for
      // the max alongside them.
      for (let i = 0; i < carves.length; i++) {
        const cut = maskHeightAt(carves[i]!, carveNoises[i]!, x, z, seaLevel);
        if (cut === null) continue;
        // `cut` is the carve's dome height: deepest at the channel's middle,
        // fading to nothing at its edge, so the banks slope into the water.
        best = Math.max(oceanFloor, best - (cut - seaLevel));
      }
      field.set(gx, gz, best);
      if (best > seaLevel + 0.2) {
        land++;
        perIsland[bestId] = (perIsland[bestId] ?? 0) + 1;
      }
    }
  }
  return { land, perIsland };
};

/**
 * Thermal erosion over the whole field: slump anything steeper than the talus
 * angle toward its neighbours. Not hydraulic — no channels, no deposition — but
 * it turns noise spikes into shapes that read as rock, and it is the difference
 * between an island you can walk on and a wall of Steep cells.
 *
 * Ocean floor is skipped: it is a flat constant and eroding it would drag the
 * shoreline down into a moat.
 */
export const erodeField = (
  field: WorldHeightField,
  settings: ErosionSettings,
  seaLevel: number,
): number => {
  let moved = 0;
  const next = new Float32Array(field.heights.length);
  for (let pass = 0; pass < settings.passes; pass++) {
    next.set(field.heights);
    for (let gz = 1; gz < field.side - 1; gz++) {
      for (let gx = 1; gx < field.side - 1; gx++) {
        const here = field.get(gx, gz);
        if (here <= seaLevel) continue;
        const n = field.get(gx, gz - 1);
        const s = field.get(gx, gz + 1);
        const w = field.get(gx - 1, gz);
        const e = field.get(gx + 1, gz);
        const slope = (Math.atan(Math.hypot((e - w) / 2, (s - n) / 2)) * 180) / Math.PI;
        if (slope < settings.minSlopeDeg) continue;
        const average = (n + s + w + e) / 4;
        next[gz * field.side + gx] = here + (average - here) * settings.strength;
        moved++;
      }
    }
    field.heights.set(next);
  }
  return moved;
};

/** Slope in degrees at a vertex, from the field's 1 m spacing. */
export const slopeAt = (field: WorldHeightField, gx: number, gz: number): number => {
  const x0 = Math.max(0, gx - 1);
  const x1 = Math.min(field.side - 1, gx + 1);
  const z0 = Math.max(0, gz - 1);
  const z1 = Math.min(field.side - 1, gz + 1);
  const dx = (field.get(x1, gz) - field.get(x0, gz)) / (x1 - x0);
  const dz = (field.get(gx, z1) - field.get(gx, z0)) / (z1 - z0);
  return (Math.atan(Math.hypot(dx, dz)) * 180) / Math.PI;
};

/**
 * One splat rule. Rules are applied IN ORDER and the last match wins, which is
 * why a rule set starts with a full-coverage base: every texel ends up with
 * exactly one layer at full weight, so nothing is left at the unblended default.
 *
 * `polygon` scopes a rule to a zone — this is how the six zones of WORLD.md §6
 * get their own eight-layer palette out of one pass instead of six passes that
 * each have to know not to touch the others.
 */
export interface SplatRule {
  readonly layer: number;
  readonly minSlopeDeg: number;
  readonly maxSlopeDeg: number;
  readonly minHeight: number;
  readonly maxHeight: number;
  /**
   * World-space ring; the rule only applies to texels inside it. Same `[x, z]`
   * tuple shape as a zone's own polygon in `@dawned/shared`, so a zone can be
   * handed straight to a rule with no conversion — a second representation of
   * "a ring on the ground" is a second place for a winding or an axis order to
   * be wrong.
   */
  readonly polygon?: readonly (readonly [number, number])[];
  /**
   * Names a zone in the map draft, whose polygon becomes this rule's ring.
   *
   * This is how a palette is authored: a rule saying "the Weald's ground cover"
   * rather than carrying 28 corners of its own. Two reasons it is not just a
   * convenience — a plan carrying six zone rings is 15 kB, which does not fit
   * in the URL an SSE endpoint has to be requested with; and a copied polygon
   * is a copy that can go stale the first time somebody drags a zone corner,
   * leaving the paint and the zone describing different ground.
   */
  readonly zoneId?: string;
}

/**
 * Resolve every `zoneId` into the polygon that zone really has.
 *
 * Throws rather than skipping: a rule pointing at a zone that is not there
 * would silently apply to the WHOLE WORLD (no polygon means no restriction),
 * repainting five zones with a sixth one's palette.
 */
export const resolveSplatZones = (
  rules: readonly SplatRule[],
  zonePolygons: ReadonlyMap<string, readonly (readonly [number, number])[]>,
): SplatRule[] =>
  rules.map((rule) => {
    if (rule.zoneId === undefined) return rule;
    const polygon = zonePolygons.get(rule.zoneId);
    if (!polygon) {
      throw new Error(
        `splat rule names zone "${rule.zoneId}", which is not in the map draft — ` +
          'an unresolved rule would paint the entire world',
      );
    }
    return { ...rule, polygon };
  });

/** Even-odd point-in-polygon — the same rule as shared's `pointInPolygon`. */
export const insidePolygon = (
  polygon: readonly (readonly [number, number])[],
  x: number,
  z: number,
): boolean => {
  let inside = false;
  for (let i = 0, j = polygon.length - 1; i < polygon.length; j = i++) {
    const [xi, zi] = polygon[i]!;
    const [xj, zj] = polygon[j]!;
    if (zi > z !== zj > z && x < ((xj - xi) * (z - zi)) / (zj - zi) + xi) {
      inside = !inside;
    }
  }
  return inside;
};

/** The layer a texel should carry, or -1 when no rule claims it. */
export const splatLayerAt = (
  rules: readonly SplatRule[],
  height: number,
  slopeDeg: number,
  x: number,
  z: number,
): number => {
  let chosen = -1;
  for (const rule of rules) {
    if (slopeDeg < rule.minSlopeDeg || slopeDeg > rule.maxSlopeDeg) continue;
    if (height < rule.minHeight || height > rule.maxHeight) continue;
    if (rule.polygon && !insidePolygon(rule.polygon, x, z)) continue;
    chosen = rule.layer;
  }
  return chosen;
};
